"use client";
import { useEffect, useState } from "react";

type User={id:string;email:string;displayName:string|null;role:string;status:string;balance:string;createdAt:string;lastLoginAt:string|null};
type Tx={id:string;type:string;status:string;amount:string;currency:string;user:{email:string;displayName:string|null};createdAt:string};
type Payment={id:string;type:string;status:string;provider:string;amount:string;currency:string;externalId:string|null;user:{email:string;displayName:string|null};createdAt:string;expiresAt:string|null};
type Settlement={id:string;provider:string;amount:string;currency:string;status:string;destination:string|null;createdAt:string};

const money=(v:string|number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v));
const date=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));

export default function Admin(){
 const [stats,setStats]=useState<any>(null),[users,setUsers]=useState<User[]>([]),[tx,setTx]=useState<Tx[]>([]),[payments,setPayments]=useState<Payment[]>([]),[settlements,setSettlements]=useState<Settlement[]>([]);
 const [q,setQ]=useState(""),[tab,setTab]=useState("overview"),[msg,setMsg]=useState(""),[setup,setSetup]=useState({setupKey:"",email:"",password:""}),[setupVisible,setSetupVisible]=useState(false),[loading,setLoading]=useState(true);
 async function load(){
  setLoading(true);
  const [a,b,c,d,e]=await Promise.all([
   fetch("/api/admin/stats"),fetch("/api/admin/users?q="+encodeURIComponent(q)),fetch("/api/admin/transactions"),
   fetch("/api/admin/payments?take=100"),fetch("/api/admin/settlements")
  ]);
  if(a.ok)setStats((await a.json()).stats); else if(a.status===401){location.href="/login";return}
  if(b.ok)setUsers((await b.json()).users||[]); if(c.ok)setTx((await c.json()).transactions||[]);
  if(d.ok)setPayments((await d.json()).payments||[]); if(e.ok)setSettlements((await e.json()).settlements||[]);
  setLoading(false);
 }
 useEffect(()=>{load()},[]);
 async function toggle(u:User){const status=u.status==="ACTIVE"?"BLOCKED":"ACTIVE";const r=await fetch(`/api/admin/users/${u.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const b=await r.json();setMsg(b?.success?"Status atualizado.":b?.error?.message||"Erro");load()}
 async function balance(id:string,type:string){const amount=prompt(type==="WITHDRAW"?"Valor do ajuste de retirada:":"Valor para adicionar:");if(!amount)return;const r=await fetch(`/api/admin/users/${id}/balance`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,type})});const b=await r.json();setMsg(b?.success?"Saldo atualizado.":b?.error?.message||"Erro");load()}
 async function requestSettlement(){const amount=prompt("Valor a solicitar para liquidação na conta da plataforma:");if(!amount)return;const destination=prompt("Identificador da conta de recebimento cadastrada no provedor (opcional):")||"";const r=await fetch("/api/admin/settlements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,destination})});const b=await r.json();setMsg(b?.success?"Solicitação registrada. A transferência real depende da gateway conectada.":b?.error?.message||"Erro");load()}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}
 async function bootstrap(e:any){e.preventDefault();const r=await fetch("/api/admin/bootstrap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(setup)});const b=await r.json();setMsg(b?.success?"Administrador criado.":b?.error?.message||"Erro");if(b?.success){setSetupVisible(false);load()}}
 const tabs=[["overview","Visão geral"],["users","Jogadores"],["payments","Depósitos / Pix"],["transactions","Transações"],["settlements","Liquidações"],["settings","Configurações"]];
 return <main className="container-page py-8 sm:py-10">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">BETWIN STUDIOS • Administração</p><h1 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Central de controle</h1><p className="mt-2 text-sm text-ink-muted">Gestão de jogadores, pagamentos, carteiras, jogos e liquidações.</p></div><button onClick={logout} className="rounded-xl border border-base-line px-4 py-2.5 text-sm font-semibold">Sair</button></div>
  {msg&&<div className="mt-5 rounded-xl border border-gold/30 bg-gold/10 p-3 text-sm text-gold">{msg}</div>}
  <div className="mt-5 flex flex-wrap justify-end gap-2"><button onClick={()=>setSetupVisible(!setupVisible)} className="rounded-xl border border-base-line px-4 py-2 text-sm font-semibold">Administrador inicial</button><button onClick={requestSettlement} className="rounded-xl bg-gold px-4 py-2 text-sm font-bold text-base">Solicitar liquidação</button></div>
  {setupVisible&&<form onSubmit={bootstrap} className="mt-4 grid gap-3 rounded-2xl border border-gold/30 bg-gold/5 p-5 md:grid-cols-4"><input placeholder="Chave de configuração" value={setup.setupKey} onChange={e=>setSetup({...setup,setupKey:e.target.value})} className="rounded-xl border border-base-line bg-base px-3 py-2 text-sm"/><input placeholder="E-mail admin" value={setup.email} onChange={e=>setSetup({...setup,email:e.target.value})} className="rounded-xl border border-base-line bg-base px-3 py-2 text-sm"/><input placeholder="Senha (10+ caracteres)" type="password" value={setup.password} onChange={e=>setSetup({...setup,password:e.target.value})} className="rounded-xl border border-base-line bg-base px-3 py-2 text-sm"/><button className="rounded-xl bg-gold px-4 py-2 font-bold text-base">Criar administrador</button></form>}
  <div className="mt-7 flex gap-2 overflow-x-auto border-b border-base-line">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap px-4 py-3 text-sm font-semibold ${tab===id?"border-b-2 border-gold text-gold":"text-ink-muted"}`}>{label}</button>)}</div>
  <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Jogadores" value={stats?.users??"—"} hint={`${stats?.active??0} ativos • ${stats?.blocked??0} bloqueados`}/><Card label="Saldo dos jogadores" value={stats?money(stats.totalBalance):"—"} hint="Saldo interno registrado"/><Card label="Depósitos pendentes" value={stats?.pendingDeposits??"—"} hint={stats?money(stats.pendingDepositAmount):"—"}/><Card label="Depósitos hoje" value={stats?money(stats.depositsToday):"—"} hint="Transações concluídas"/></section>
  {tab==="overview"&&<div className="mt-7 grid gap-5 lg:grid-cols-2"><Panel title="Controle financeiro"><div className="grid gap-3 sm:grid-cols-2">{["Depósitos e Pix","Pedidos de retirada","Carteiras dos jogadores","Transações e auditoria","Liquidação da plataforma","Integração por webhook"].map(x=><div key={x} className="rounded-xl border border-base-line/70 bg-base px-4 py-3 text-sm">✓ {x}</div>)}</div></Panel><Panel title="Integração da gateway"><p className="text-sm leading-6 text-ink-muted">Os pedidos são registrados internamente e a gateway pode confirmar pagamentos por webhook. A liquidação para a conta da plataforma fica registrada como uma operação separada, pronta para ser executada pelo provedor conectado.</p><div className="mt-4 rounded-xl bg-gold/10 p-4 text-sm text-gold">Depósito: <code>/api/payments/deposit</code> • Liquidação: <code>/api/admin/settlements</code></div></Panel></div>}
  {tab==="users"&&<Users users={users} q={q} setQ={setQ} load={load} loading={loading} toggle={toggle} balance={balance}/>}
  {tab==="payments"&&<Payments payments={payments}/>}
  {tab==="transactions"&&<Transactions tx={tx}/>}
  {tab==="settlements"&&<Settlements settlements={settlements} onRequest={requestSettlement}/>}
  {tab==="settings"&&<Panel title="Configurações"><div className="grid gap-3 sm:grid-cols-2"><Info k="Banco" v="PostgreSQL + Prisma"/><Info k="Autenticação" v="Sessão HTTP-only assinada"/><Info k="Catálogo" v="BigBang via servidor"/><Info k="Pagamentos" v="Gateway plugável + webhook"/><Info k="Liquidação" v="Provêdor externo obrigatório"/><Info k="Ambiente" v={process.env.NODE_ENV}/></div></Panel>}
 </main>
}
function Panel({title,children}:{title:string;children:any}){return <section className="rounded-2xl border border-base-line bg-base-surface p-6"><h2 className="font-display text-xl font-semibold mb-5">{title}</h2>{children}</section>}
function Card({label,value,hint}:{label:string;value:string|number;hint:string}){return <div className="rounded-2xl border border-base-line bg-base-surface p-5"><p className="text-sm text-ink-muted">{label}</p><p className="mt-2 font-display text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-ink-faint">{hint}</p></div>}
function Info({k,v}:{k:string;v:string}){return <div className="rounded-xl border border-base-line bg-base p-4"><p className="text-xs text-ink-muted">{k}</p><p className="mt-1 font-semibold">{v}</p></div>}
function Users({users,q,setQ,load,loading,toggle,balance}:any){return <section className="mt-7 rounded-2xl border border-base-line bg-base-surface p-5"><div className="flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Buscar e-mail ou nome" className="flex-1 rounded-xl border border-base-line bg-base px-4 py-2.5 text-sm"/><button onClick={load} className="rounded-xl bg-gold px-5 py-2.5 text-sm font-bold text-base">Buscar</button></div><Table><thead><tr><Th>Jogador</Th><Th>Status</Th><Th>Saldo</Th><Th>Cadastro</Th><Th>Ações</Th></tr></thead><tbody>{users.map((u:User)=><tr key={u.id} className="border-b border-base-line/60"><td className="p-3"><b>{u.displayName||"Sem nome"}</b><div className="text-xs text-ink-muted">{u.email}</div></td><td className="p-3">{u.status==="ACTIVE"?"Ativo":"Bloqueado"}</td><td className="p-3 font-semibold">{money(u.balance)}</td><td className="p-3 text-ink-muted">{date(u.createdAt)}</td><td className="p-3 flex flex-wrap gap-2"><button onClick={()=>balance(u.id,"DEPOSIT")} className="rounded-lg border border-base-line px-3 py-1.5 text-xs">+ Saldo</button><button onClick={()=>balance(u.id,"WITHDRAW")} className="rounded-lg border border-base-line px-3 py-1.5 text-xs">− Saldo</button><button onClick={()=>toggle(u)} className="rounded-lg border border-base-line px-3 py-1.5 text-xs">{u.status==="ACTIVE"?"Bloquear":"Desbloquear"}</button></td></tr>)}</tbody></Table>{!users.length&&!loading&&<p className="py-10 text-center text-sm text-ink-muted">Nenhum jogador encontrado.</p>}</section>}
function Payments({payments}:any){return <section className="mt-7"><Panel title="Depósitos / Pix"><Table><thead><tr><Th>Data</Th><Th>Jogador</Th><Th>Provedor</Th><Th>Status</Th><Th>Valor</Th><Th>ID externo</Th></tr></thead><tbody>{payments.filter((p:Payment)=>p.type==="DEPOSIT").map((p:Payment)=><tr key={p.id} className="border-b border-base-line/60"><td className="p-3">{date(p.createdAt)}</td><td className="p-3">{p.user.email}</td><td className="p-3">{p.provider}</td><td className="p-3">{p.status}</td><td className="p-3 font-semibold">{money(p.amount)}</td><td className="p-3 text-xs">{p.externalId||"—"}</td></tr>)}</tbody></Table></Panel></section>}
function Transactions({tx}:any){return <section className="mt-7"><Panel title="Livro de transações"><Table><thead><tr><Th>Data</Th><Th>Jogador</Th><Th>Tipo</Th><Th>Status</Th><Th>Valor</Th></tr></thead><tbody>{tx.map((t:Tx)=><tr key={t.id} className="border-b border-base-line/60"><td className="p-3">{date(t.createdAt)}</td><td className="p-3">{t.user.email}</td><td className="p-3">{t.type}</td><td className="p-3">{t.status}</td><td className="p-3 font-semibold">{money(t.amount)}</td></tr>)}</tbody></Table></Panel></section>}
function Settlements({settlements,onRequest}:any){return <section className="mt-7"><Panel title="Liquidações da plataforma"><button onClick={onRequest} className="mb-5 rounded-xl bg-gold px-4 py-2 text-sm font-bold text-base">Nova solicitação</button><Table><thead><tr><Th>Data</Th><Th>Valor</Th><Th>Status</Th><Th>Provedor</Th><Th>Destino</Th></tr></thead><tbody>{settlements.map((s:Settlement)=><tr key={s.id} className="border-b border-base-line/60"><td className="p-3">{date(s.createdAt)}</td><td className="p-3 font-semibold">{money(s.amount)}</td><td className="p-3">{s.status}</td><td className="p-3">{s.provider}</td><td className="p-3">{s.destination||"Conta configurada no provedor"}</td></tr>)}</tbody></Table></Panel></section>}
function Table({children}:{children:any}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm">{children}</table></div>}
function Th({children}:{children:any}){return <th className="border-b border-base-line p-3 text-xs uppercase tracking-wide text-ink-muted">{children}</th>}
